<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author:    Ashley Kitson                                                  //
// Copyright: (c) 2004, Ashley Kitson
// URL:       http://xoobs.net			                                     //
// Project:   The XOOPS Project (http://www.xoops.org/)                      //
// Module:    Code Data Management (CDM)                                     //
// ------------------------------------------------------------------------- //
/** 
 * Xoops module Installation parameters
 *
 * This file conforms to the Xoops standard for the xoops_version.php file.
 * Constant declarations beginning _MI_ are contained in language/../modinfo.php
 * 
 * @author Ashley Kitson http://xoobs.net
 * @copyright (c) 2004, Ashley Kitson
 * @package CDM
 * @version 1.5
 * @subpackage Installation
 * @access private
 * @global array Module Installation array as per Xoops
 */
global $modversion;


$modversion['name'] = _MI_CDM_NAME;
$modversion['version'] = 1.5;
$modversion['description'] = _MI_CDM_DESC;
$modversion['credits'] = "Ashley Kitson<br />( http://xoobs.netk/ )";
$modversion['author'] = "Ashley Kitson";
$modversion['help'] = "cdmhelp.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/cdm_slogo.png";
$modversion['dirname'] = "xbs_cdm";
$modversion['onUpdate'] = "install_funcs.php";
$modversion['onInstall'] = "install_funcs.php";
$modversion['onUninstall'] = "install_funcs.php";



// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/xbs_cdm_mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "cdm_meta";
$modversion['tables'][1] = "cdm_code";
$modversion['tables'][2] = "cdm_list";

// Main Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_CDM_SMNAME1;
$modversion['sub'][1]['url'] = "cdm_codes_list.php";

// Templates
$modversion['templates'][1]['file'] = 'cdm_list_codes.tpl';
$modversion['templates'][1]['description'] = 'Simple list of codes';
$modversion['templates'][2]['file'] = 'cdm_index.tpl';
$modversion['templates'][2]['description'] = 'Select and edit set of codes';
//$modversion['templates'][3]['file'] = 'cdm_meta_edit.tpl';
//$modversion['templates'][3]['description'] = 'Edit a meta record';
//$modversion['templates'][4]['file'] = 'cdm_codes_edit.tpl';
//$modversion['templates'][4]['description'] = 'Edit a code record';
$modversion['templates'][3]['file'] = 'cdm_db_update.tpl';
$modversion['templates'][3]['description'] = 'Edit a code record';

// Admin things
// Admin menu things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['hasSearch'] = 0;
$modversion['hasComments'] = 0;
$modversion['hasNotification'] = 0;

// CDM Configuration items

$modversion['config'][1]['name'] = 'def_lang';
$modversion['config'][1]['title'] = '_MI_CDM_DEFLANGNAME';
$modversion['config'][1]['description'] = '_MI_CDM_DEFLANGNAMEDESC';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = 'EN';
$modversion['config'][1]['options'] = array(
'AF - Afrikaans' => 'AF',
'AR - Arabic (Base)' => 'AR',
'ARAE - Arabic (UAE)' => 'ARAE',
'ARBH - Arabic (Bahrain)' => 'ARBH',
'ARDZ - Arabic (Algeria)' => 'ARDZ',
'AREG - Arabic (Egypt)' => 'AREG',
'ARIQ - Arabic (Iraq)' => 'ARIQ',
'ARJO - Arabic (Jordan)' => 'ARJO',
'ARKW - Arabic (Kuwait)' => 'ARKW',
'ARLB - Arabic (Lebanon)' => 'ARLB',
'ARLY - Arabic (Libya)' => 'ARLY',
'ARMA - Arabic (Morocco)' => 'ARMA',
'AROM - Arabic (Oman)' => 'AROM',
'ARQA - Arabic (Qatar)' => 'ARQA',
'ARSA - Arabic (Saudi Arabia)' => 'ARSA',
'ARSY - Arabic (Syria)' => 'ARSY',
'ARTN - Arabic (Tunisia)' => 'ARTN',
'ARYE - Arabic (Yemen)' => 'ARYE',
'BE - Belarussian' => 'BE',
'BG - Bulgarian' => 'BG',
'CA - Catalan' => 'CA',
'CS - Czech' => 'CS',
'DA - Danish' => 'DA',
'DE - German (Germany)' => 'DE',
'DEAT - German (Austria)' => 'DEAT',
'DECH - German (Switzerland)' => 'DECH',
'DELI - German (Leichtenstein)' => 'DELI',
'DELU - German (Luxembourgh)' => 'DELU',
'EL - Greek' => 'EL',
'EN - English (Base)' => 'EN',
'ENAU - English (Australian)' => 'ENAU',
'ENBZ - English (Belize)' => 'ENBZ',
'ENCA - English (Canadian)' => 'ENCA',
'ENGB - English (United Kingdom)' => 'ENGB',
'ENIE - English (Ireland)' => 'ENIE',
'ENJM - English (Jamaica)' => 'ENJM',
'ENKY - English (Caribbean)' => 'ENKY',
'ENNZ - English (New Zealand)' => 'ENNZ',
'ENTT - English (Trinidad)' => 'ENTT',
'ENUS - English (American)' => 'ENUS',
'ENZA - English (South Africa)' => 'ENZA',
'ES - Spanish (Modern)' => 'ES',
'ESAR - Spanish (Argentina)' => 'ESAR',
'ESBO - Spanish (Bolivia)' => 'ESBO',
'ESCL - Spanish (Chile)' => 'ESCL',
'ESCO - Spanish (Colombia)' => 'ESCO',
'ESCR - Spanish (Costa Rica)' => 'ESCR',
'ESDO - Spanish (Dominican Republic)' => 'ESDO',
'ESEC - Spanish (Ecuador)' => 'ESEC',
'ESGT - Spanish (Guatemala)' => 'ESGT',
'ESHN - Spanish (Honduras)' => 'ESHN',
'ESMX - Spanish (Mexico)' => 'ESMX',
'ESNI - Spanish (Nicaragua)' => 'ESNI',
'ESPA - Spanish (Panama)' => 'ESPA',
'ESPE - Spanish (Peru)' => 'ESPE',
'ESPR - Spanish (Puerto Rico)' => 'ESPR',
'ESPY - Spanish (Paraguay)' => 'ESPY',
'ESSV - Spanish (El Salvador)' => 'ESSV',
'ESUY - Spanish (Uruguay)' => 'ESUY',
'ESVE - Spanish (Venezuela)' => 'ESVE',
'ET - Estonian' => 'ET',
'EU - Basque' => 'EU',
'FA - Farsi' => 'FA',
'FI - Finnish' => 'FI',
'FO - Faroese' => 'FO',
'FR - French (France)' => 'FR',
'FRBE - French (Belgium)' => 'FRBE',
'FRCA - French (Canada)' => 'FRCA',
'FRCH - French (Switzerland)' => 'FRCH',
'FRLU - French (Luxembourgh)' => 'FRLU',
'GD - Gaelic (Scots)' => 'GD',
'HE - Hebrew' => 'HE',
'HI - Hindi' => 'HI',
'HR - Croatian' => 'HR',
'HU - Hungarian' => 'HU',
'IN - Indonesian' => 'IN',
'IS - Icelandic' => 'IS',
'IT - Italian (Italy)' => 'IT',
'ITCH - Italian (Switzerland)' => 'ITCH',
'JA - Japanese' => 'JA',
'JI - Yiddish' => 'JI',
'KO - Korean (Extended Wansung)' => 'KO',
'LT - Lithuanian' => 'LT',
'LV - Lettish' => 'LV',
'MK - Macedonian' => 'MK',
'MS - Malay (Malaysia)' => 'MS',
'MT - Maltese' => 'MT',
'NL - Dutch (Nederland)' => 'NL',
'NLBE - Dutch (Belgium)' => 'NLBE',
'NO - Norwegian (Bokmal)' => 'NO',
'PL - Polish' => 'PL',
'PT - Portuguese' => 'PT',
'PTBR - Portuguese (Brazil)' => 'PTBR',
'RM - Rhaeto-Romance' => 'RM',
'RO - Romanian' => 'RO',
'ROMO - Romanian (Moldova)' => 'ROMO',
'RU - Russian' => 'RU',
'RUMO - Russian (Moldova)' => 'RUMO',
'SK - Slovak' => 'SK',
'SL - Slovenian' => 'SL',
'SQ - Albanian' => 'SQ',
'SR - Serbian (Cyrillic)' => 'SR',
'SV - Swedish' => 'SV',
'SVFI - Swedish (Finland)' => 'SVFI',
'SX - Sutu' => 'SX',
'TH - Thai' => 'TH',
'TN - Setsuana' => 'TN',
'TR - Turkish' => 'TR',
'TS - Tsonga' => 'TS',
'UK - Ukrainian' => 'UK',
'UR - Urdu (Pakistan)' => 'UR',
'VI - Vietnamese' => 'VI',
'XH - Xhosa' => 'XH',
'ZH - Chinese (Base)' => 'ZH',
'ZHCN - Chinese (PRC)' => 'ZHCN',
'ZHHK - Chinese (Hong Kong)' => 'ZHHK',
'ZHSG - Chinese (Singapore)' => 'ZHSG',
'ZHTW - Chinese (Taiwan)' => 'ZHTW',
'ZU - Zulu' => 'ZU',);

$modversion['config'][2]['name'] = 'def_codeset';
$modversion['config'][2]['title'] = '_MI_CDM_DEFCODESETNAME';
$modversion['config'][2]['description'] = '_MI_CDM_DEFCODESETNAMEDESC';
$modversion['config'][2]['formtype'] = 'text';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = 'BASE';

// Blocks
$modversion['blocks'][1]['file'] = 'cdm_block_codelookup.php';
$modversion['blocks'][1]['name'] = _MI_CDM_BLOCK_CODELOOKUPNAME;
$modversion['blocks'][1]['description'] = _MI_CDM_BLOCK_CODELOOKUPDESC;
$modversion['blocks'][1]['show_func'] = "b_cdm_codelookup_show";
$modversion['blocks'][1]['edit_func'] = "b_cdm_codelookup_edit";
$modversion['blocks'][1]['options'] = "COUNTRY|EN    |0|0"; //Setname | Language | Allow set change | Allow language change
$modversion['blocks'][1]['template'] = "cdm_block_codelookup.tpl" ;

?>
